name: Debian based build

on:
  push:
    branches: [ "main", "premain", "feature/make_install_setup_automatic" ]
  pull_request:
    branches: [ "main", "premain", "feature/make_install_setup_automatic" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      
    - name: Download dependencies
      run: sudo apt install make qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools freeglut3-dev 

    - name: qmake
      run: cd Projet && qmake
      
    - name: make
      run: cd Projet && make
    
    - name: dpkg
      run: cd Projet && ../.github/workflows/debian-build.sh

    - name: Publish .deb     
      uses: actions/download-artifact@v3.0.0
      with:
         name: "Asteriads.deb"
         path: Projet/Asteriads_0.0.3-1_amd64.deb
